const { Product } = require("../models");

const productData = [
  {
    image: "https://source.unsplash.com/random/900×700/?Vinyl,Records",
    product_name: "Top 40 Music Compilation Vinyl Record",
    price: 12.99,
    stock: 50,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Male,Shorts",
    product_name: "Cargo Shorts",
    price: 29.99,
    stock: 22,
    category_id: 2,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Denim,Jacket",
    product_name: "Denim Jacket",
    price: 49.99,
    stock: 18,
    category_id: 1,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Running,Shoes",
    product_name: "Running Shoes",
    price: 79.99,
    stock: 30,
    category_id: 5,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Sunglasses",
    product_name: "Designer Sunglasses",
    price: 99.99,
    stock: 8,
    category_id: 4,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Vinyl,Records",
    product_name: "Classic Rock Vinyl Record Set",
    price: 29.99,
    stock: 40,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Swim,Shorts",
    product_name: "Swim Shorts",
    price: 24.99,
    stock: 15,
    category_id: 2,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Plain,Shirt",
    product_name: "Plain T-Shirt",
    price: 14.99,
    stock: 14,
    category_id: 1,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Jordans",
    product_name: "Running Sneakers",
    price: 90.0,
    stock: 25,
    category_id: 5,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Baseball,Hat",
    product_name: "Branded Baseball Hat",
    price: 22.99,
    stock: 12,
    category_id: 4,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Vinyl,Records",
    product_name: "Top 40 Music Compilation Vinyl Record",
    price: 12.99,
    stock: 50,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Male,Shorts",
    product_name: "Cargo Shorts",
    price: 29.99,
    stock: 22,
    category_id: 2,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Denim,Jacket",
    product_name: "Denim Jacket",
    price: 49.99,
    stock: 18,
    category_id: 1,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Running,Shoes",
    product_name: "Running Shoes",
    price: 79.99,
    stock: 30,
    category_id: 5,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Sunglasses",
    product_name: "Designer Sunglasses",
    price: 99.99,
    stock: 8,
    category_id: 4,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Vinyl,Records",
    product_name: "Classic Rock Vinyl Record Set",
    price: 29.99,
    stock: 40,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Swim,Shorts",
    product_name: "Swim Shorts",
    price: 24.99,
    stock: 15,
    category_id: 2,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Black,Dress",
    product_name: "Black Evening Dress",
    price: 89.99,
    stock: 10,
    category_id: 1,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Basketball,Shoes",
    product_name: "Basketball Shoes",
    price: 109.99,
    stock: 20,
    category_id: 5,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Beanie,Hat",
    product_name: "Knit Beanie Hat",
    price: 14.99,
    stock: 25,
    category_id: 4,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Pop,Records",
    product_name: "Best of Pop Music Vinyl Record",
    price: 16.99,
    stock: 35,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Denim,Shorts",
    product_name: "Denim Shorts",
    price: 34.99,
    stock: 18,
    category_id: 2,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Leather,Jacket",
    product_name: "Leather Jacket",
    price: 79.99,
    stock: 15,
    category_id: 1,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Casual,Shoes",
    product_name: "Casual Sneakers",
    price: 64.99,
    stock: 20,
    category_id: 5,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Wide,Brim,Hat",
    product_name: "Wide Brim Hat",
    price: 19.99,
    stock: 12,
    category_id: 4,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Classic,Records",
    product_name: "Classic Hits Vinyl Record Set",
    price: 24.99,
    stock: 45,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Sport,Shorts",
    product_name: "Sport Shorts",
    price: 19.99,
    stock: 30,
    category_id: 2,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Leather,Belt",
    product_name: "Leather Belt",
    price: 29.99,
    stock: 15,
    category_id: 4,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Jazz,Records",
    product_name: "Jazz Music Vinyl Record",
    price: 18.99,
    stock: 30,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Printed,Shirt",
    product_name: "Printed T-Shirt",
    price: 14.99,
    stock: 20,
    category_id: 1,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Soccer,Cleats",
    product_name: "Soccer Cleats",
    price: 79.99,
    stock: 15,
    category_id: 5,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Winter,Hat",
    product_name: "Winter Hat",
    price: 12.99,
    stock: 18,
    category_id: 4,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Hip,Hop,Records",
    product_name: "Hip Hop Music Vinyl Record",
    price: 21.99,
    stock: 25,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Sweatpants",
    product_name: "Sweatpants",
    price: 24.99,
    stock: 20,
    category_id: 2,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Leather,Wallet",
    product_name: "Leather Wallet",
    price: 39.99,
    stock: 15,
    category_id: 4,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Classical,Records",
    product_name: "Classical Music Vinyl Record",
    price: 17.99,
    stock: 30,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Striped,Shirt",
    product_name: "Striped T-Shirt",
    price: 16.99,
    stock: 20,
    category_id: 1,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Hiking,Shoes",
    product_name: "Hiking Shoes",
    price: 89.99,
    stock: 15,
    category_id: 5,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Sun,Hat",
    product_name: "Sun Hat",
    price: 14.99,
    stock: 18,
    category_id: 4,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Country,Records",
    product_name: "Country Music Vinyl Record",
    price: 19.99,
    stock: 30,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Hoodie",
    product_name: "Hoodie",
    price: 34.99,
    stock: 20,
    category_id: 2,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Canvas,Shoes",
    product_name: "Canvas Shoes",
    price: 29.99,
    stock: 15,
    category_id: 5,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Snapback,Hat",
    product_name: "Snapback Hat",
    price: 19.99,
    stock: 18,
    category_id: 4,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Metal,Records",
    product_name: "Metal Music Vinyl Record",
    price: 16.99,
    stock: 30,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Graphic,Shirt",
    product_name: "Graphic T-Shirt",
    price: 18.99,
    stock: 20,
    category_id: 1,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Skateboarding,Shoes",
    product_name: "Skateboarding Shoes",
    price: 79.99,
    stock: 15,
    category_id: 5,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Bucket,Hat",
    product_name: "Bucket Hat",
    price: 14.99,
    stock: 18,
    category_id: 4,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Electronic,Records",
    product_name: "Electronic Music Vinyl Record",
    price: 21.99,
    stock: 30,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Cargo,Pants",
    product_name: "Cargo Pants",
    price: 32.99,
    stock: 20,
    category_id: 2,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Leather,Handbag",
    product_name: "Leather Handbag",
    price: 69.99,
    stock: 15,
    category_id: 4,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Rock,Records",
    product_name: "Rock Music Vinyl Record",
    price: 15.99,
    stock: 30,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Printed,Dress",
    product_name: "Printed Dress",
    price: 49.99,
    stock: 20,
    category_id: 1,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Football,Cleats",
    product_name: "Football Cleats",
    price: 89.99,
    stock: 15,
    category_id: 5,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Fedora,Hat",
    product_name: "Fedora Hat",
    price: 24.99,
    stock: 18,
    category_id: 4,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Indie,Records",
    product_name: "Indie Music Vinyl Record",
    price: 17.99,
    stock: 30,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Chinos",
    product_name: "Chinos",
    price: 39.99,
    stock: 20,
    category_id: 2,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Crossbody,Bag",
    product_name: "Crossbody Bag",
    price: 49.99,
    stock: 15,
    category_id: 4,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Reggae,Records",
    product_name: "Reggae Music Vinyl Record",
    price: 18.99,
    stock: 30,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?V-neck,Shirt",
    product_name: "V-neck T-Shirt",
    price: 16.99,
    stock: 20,
    category_id: 1,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Volleyball,Shoes",
    product_name: "Volleyball Shoes",
    price: 79.99,
    stock: 15,
    category_id: 5,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Straw,Hat",
    product_name: "Straw Hat",
    price: 12.99,
    stock: 18,
    category_id: 4,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Blues,Records",
    product_name: "Blues Music Vinyl Record",
    price: 21.99,
    stock: 30,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Leggings",
    product_name: "Leggings",
    price: 24.99,
    stock: 20,
    category_id: 2,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Messenger,Bag",
    product_name: "Messenger Bag",
    price: 59.99,
    stock: 15,
    category_id: 4,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Rap,Records",
    product_name: "Rap Music Vinyl Record",
    price: 19.99,
    stock: 30,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Floral,Dress",
    product_name: "Floral Dress",
    price: 54.99,
    stock: 20,
    category_id: 1,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Golf,Shoes",
    product_name: "Golf Shoes",
    price: 99.99,
    stock: 15,
    category_id: 5,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Beanie,Hat",
    product_name: "Beanie Hat",
    price: 14.99,
    stock: 18,
    category_id: 4,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Punk,Records",
    product_name: "Punk Music Vinyl Record",
    price: 16.99,
    stock: 30,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Polo,Shirt",
    product_name: "Polo Shirt",
    price: 24.99,
    stock: 20,
    category_id: 1,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Tennis,Shoes",
    product_name: "Tennis Shoes",
    price: 79.99,
    stock: 15,
    category_id: 5,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Beret",
    product_name: "Beret",
    price: 19.99,
    stock: 18,
    category_id: 4,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Hipster,Records",
    product_name: "Hipster Music Vinyl Record",
    price: 18.99,
    stock: 30,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Joggers",
    product_name: "Joggers",
    price: 29.99,
    stock: 20,
    category_id: 2,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Backpack",
    product_name: "Backpack",
    price: 39.99,
    stock: 15,
    category_id: 4,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Funk,Records",
    product_name: "Funk Music Vinyl Record",
    price: 17.99,
    stock: 30,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Hawaiian,Shirt",
    product_name: "Hawaiian Shirt",
    price: 21.99,
    stock: 20,
    category_id: 1,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Plain,Shirt",
    product_name: "Plain T-Shirt",
    price: 14.99,
    stock: 14,
    category_id: 1,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Jordans",
    product_name: "Running Sneakers",
    price: 90.0,
    stock: 25,
    category_id: 5,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Baseball,Hat",
    product_name: "Branded Baseball Hat",
    price: 22.99,
    stock: 12,
    category_id: 4,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Vinyl,Records",
    product_name: "Top 40 Music Compilation Vinyl Record",
    price: 12.99,
    stock: 50,
    category_id: 3,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Male,Shorts",
    product_name: "Cargo Shorts",
    price: 29.99,
    stock: 22,
    category_id: 2,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Plain,Shirt",
    product_name: "Plain T-Shirt",
    price: 14.99,
    stock: 14,
    category_id: 1,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Jordans",
    product_name: "Running Sneakers",
    price: 90.0,
    stock: 25,
    category_id: 5,
  },
  {
    image: "https://source.unsplash.com/random/900×700/?Baseball,Hat",
    product_name: "Branded Baseball Hat",
    price: 22.99,
    stock: 12,
    category_id: 4,
  }
];

const seedProducts = () => Product.bulkCreate(productData);

module.exports = seedProducts;
